#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build ~/.hammerspoon/init.lua -- Region Manager v2.1.0 with multi-screen support"""
import json

lines = []
A = lines.append

A("-- ============================================================")
A("-- Region Manager - Hammerspoon v2.1.0")
A("-- Multi-screen: per-screen wireframe colors + bounds constraint")
A("-- ============================================================")
A("")
A('local ok, err = pcall(function() hs.ipc.cliInstall() end)')
A("")
A('local CONFIG_FILE = os.getenv("HOME") .. "/.screen_regions.json"')
A("")
A("local overlays = {}")
A("local editMode = false")
A("")
A("-- ============================================================")
A("-- Screen color palette: each screen index gets a distinct color")
A("-- Screen 0 (built-in) = blue, Screen 1 (external) = orange,")
A("-- Screen 2+ = green / purple / teal")
A("-- ============================================================")
A("local SCREEN_COLORS = {")
A("    {")
A("        name      = 'Built-in',")
A("        border    = { red = 0.20, green = 0.50, blue = 1.00, alpha = 1.0 },")
A("        fill      = { red = 0.20, green = 0.50, blue = 1.00, alpha = 0.10 },")
A("        accent    = { red = 0.20, green = 0.50, blue = 1.00, alpha = 0.9 },")
A("    },")
A("    {")
A("        name      = 'External-1',")
A("        border    = { red = 1.00, green = 0.60, blue = 0.00, alpha = 1.0 },")
A("        fill      = { red = 1.00, green = 0.60, blue = 0.00, alpha = 0.10 },")
A("        accent    = { red = 1.00, green = 0.60, blue = 0.00, alpha = 0.9 },")
A("    },")
A("    {")
A("        name      = 'External-2',")
A("        border    = { red = 0.20, green = 0.80, blue = 0.30, alpha = 1.0 },")
A("        fill      = { red = 0.20, green = 0.80, blue = 0.30, alpha = 0.10 },")
A("        accent    = { red = 0.20, green = 0.80, blue = 0.30, alpha = 0.9 },")
A("    },")
A("    {")
A("        name      = 'External-3',")
A("        border    = { red = 0.70, green = 0.30, blue = 1.00, alpha = 1.0 },")
A("        fill      = { red = 0.70, green = 0.30, blue = 1.00, alpha = 0.10 },")
A("        accent    = { red = 0.70, green = 0.30, blue = 1.00, alpha = 0.9 },")
A("    },")
A("    {")
A("        name      = 'External-4',")
A("        border    = { red = 0.00, green = 0.80, blue = 0.80, alpha = 1.0 },")
A("        fill      = { red = 0.00, green = 0.80, blue = 0.80, alpha = 0.10 },")
A("        accent    = { red = 0.00, green = 0.80, blue = 0.80, alpha = 0.9 },")
A("    },")
A("}")
A("")
A("local COLORS = {")
A("    red      = { red = 1.0, green = 0.27, blue = 0.27, alpha = 0.9 },")
A("    green    = { red = 0.13, green = 0.55, blue = 0.13, alpha = 0.9 },")
A("    running  = { red = 0.85, green = 0.20, blue = 0.20, alpha = 0.9 },")
A("    white    = { white = 1.0, alpha = 1.0 },")
A("    dark     = { white = 0.15, alpha = 1.0 },")
A("}")
A("")
A("-- ============================================================")
A("-- Screen helpers")
A("-- ============================================================")
A("")
A("local function getScreenByPos(x, y)")
A("    local scr = hs.screen.find({ x = x, y = y })")
A("    if not scr then return nil, -1 end")
A("    local all = hs.screen.allScreens()")
A("    local idx = -1")
A("    for i, s in ipairs(all) do")
A("        if s:id() == scr:id() then idx = i - 1; break end")
A("    end")
A("    return scr, idx")
A("end")
A("")
A("local function getScreenFrame(scr)")
A("    if not scr then return { x = 0, y = 0, w = 1920, h = 1080 } end")
A("    local f = scr:fullFrame()")
A("    return { x = f.x, y = f.y, w = f.w, h = f.h }")
A("end")
A("")
A("local function getScreenColor(idx)")
A("    if idx < 0 or idx >= #SCREEN_COLORS then")
A("        return SCREEN_COLORS[1]")
A("    end")
A("    return SCREEN_COLORS[idx + 1]")
A("end")
A("")
A("local function getScreenName(idx)")
A("    local sc = getScreenColor(idx)")
A("    if idx < 0 then return 'unknown' end")
A("    return sc.name .. ' (screen #' .. idx .. ')'")
A("end")
A("")
A("local function regionCenterX(r)")
A("    return r.x + r.width / 2")
A("end")
A("")
A("local function regionCenterY(r)")
A("    return r.y + r.height / 2")
A("end")
A("")
A("-- ============================================================")
A("-- JSON persistence")
A("-- ============================================================")
A("")
A("local function readConfig()")
A('    local f = io.open(CONFIG_FILE, "r")')
A("    if not f then return {} end")
A('    local content = f:read("*all")')
A("    f:close()")
A("    local ok, data = pcall(hs.json.decode, content)")
A("    if not ok then return {} end")
A("    return data.regions or {}")
A("end")
A("")
A("local function writeConfig(regions)")
A('    local data = { version = "1.0", regions = regions }')
A('    local f = io.open(CONFIG_FILE, "w")')
A("    if not f then return end")
A("    f:write(hs.json.encode(data))")
A("    f:close()")
A("end")
A("")
A("local function pointInRect(px, py, rx, ry, rw, rh)")
A("    return px >= rx and px <= rx + rw and py >= ry and py <= ry + rh")
A("end")
A("")
A("-- ============================================================")
A("-- Redraw: use screen-specific colors for border & fill")
A("-- ============================================================")
A("")
A("local function redraw(state)")
A("    local w = state.width")
A("    local h = state.height")
A("    local sc = state.screenColor")
A("")
A("    -- Layer 1: background fill (screen-specific tint)")
A("    state.canvas[1] = {")
A('        type = "rectangle", action = "fill",')
A("        fillColor = sc.fill,")
A("        frame = { x = 0, y = 0, w = w, h = h },")
A("        roundedRectRadii = { xRadius = 8, yRadius = 8 },")
A("    }")
A("")
A("    -- Layer 2: border (screen-specific color)")
A("    state.canvas[2] = {")
A('        type = "rectangle", action = "stroke",')
A("        strokeColor = sc.border,")
A("        strokeWidth = 3,")
A("        frame = { x = 1.5, y = 1.5, w = w - 3, h = h - 3 },")
A("        roundedRectRadii = { xRadius = 8, yRadius = 8 },")
A("    }")
A("")
A("    -- Layer 3: close button (top-right)")
A("    local cx = w - 18")
A("    local cy = 2")
A("    state.closeFrame = { x = cx, y = cy, w = 16, h = 16 }")
A("    state.canvas[3] = {")
A('        type = "rectangle", action = "fill",')
A("        fillColor = COLORS.red,")
A("        frame = state.closeFrame,")
A("        roundedRectRadii = { xRadius = 3, yRadius = 3 },")
A("    }")
A("    state.canvas[4] = {")
A('        type = "text", text = "x",')
A("        textColor = COLORS.white, textSize = 12, textAlignment = 'center',")
A("        frame = { x = cx, y = cy + 1, w = 16, h = 15 },")
A("    }")
A("")
A("    -- Layer 5: screen label (top-left, small)")
A("    local label = 'S' .. state.screenIndex")
A("    state.canvas[7] = {")
A('        type = "text", text = label,')
A("        textColor = sc.border, textSize = 9, textAlignment = 'left',")
A("        frame = { x = 6, y = 3, w = 24, h = 14 },")
A("    }")
A("")
A("    -- Layer 6-7: Start / Stop button (bottom-center)")
A("    local bw = 64")
A("    local bh = 22")
A("    local bx = math.floor((w - bw) / 2)")
A("    local by = h - bh - 4")
A("    state.btnFrame = { x = bx, y = by, w = bw, h = bh }")
A("")
A("    if state.running then")
A("        state.canvas[5] = {")
A('            type = "rectangle", action = "fill",')
A("            fillColor = COLORS.running,")
A("            frame = state.btnFrame,")
A("            roundedRectRadii = { xRadius = 4, yRadius = 4 },")
A("        }")
A("        state.canvas[6] = {")
A('            type = "text", text = state.runCount .. " times",')
A("            textColor = COLORS.white, textSize = 9, textAlignment = 'center',")
A("            frame = { x = bx, y = by + 2, w = bw, h = bh - 2 },")
A("        }")
A("    else")
A("        state.canvas[5] = {")
A('            type = "rectangle", action = "fill",')
A("            fillColor = COLORS.green,")
A("            frame = state.btnFrame,")
A("            roundedRectRadii = { xRadius = 4, yRadius = 4 },")
A("        }")
A("        state.canvas[6] = {")
A('            type = "text", text = "Start",')
A("            textColor = COLORS.white, textSize = 10, textAlignment = 'center',")
A("            frame = { x = bx, y = by + 2, w = bw, h = bh - 2 },")
A("        }")
A("    end")
A("end")
A("")
A("-- ============================================================")
A("-- Click & scroll operations (constrained to own screen)")
A("-- ============================================================")
A("")
A("local function doClick(state)")
A("    local cx = state.savedX + state.width / 2")
A("    local cy = state.savedY + state.height / 2")
A("")
A("    -- Ensure click stays within the region's screen bounds")
A("    local sf = state.screenFrame")
A("    cx = math.max(sf.x + 5, math.min(sf.x + sf.w - 5, cx))")
A("    cy = math.max(sf.y + 5, math.min(sf.y + sf.h - 5, cy))")
A("")
A("    state.canvas:hide()")
A("    hs.timer.doAfter(0.08, function()")
A("        hs.eventtap.leftClick({ x = cx, y = cy })")
A("        hs.timer.doAfter(0.15, function()")
A("            state.canvas:show()")
A("            if state.running then")
A("                state.runCount = state.runCount + 1")
A("                if state.canvas and state.canvas[6] then")
A('                    state.canvas[6].text = state.runCount .. " times"')
A("                end")
A("            end")
A("        end)")
A("    end)")
A("end")
A("")
A("local function runStep(state, step)")
A("    if not state.running then")
A("        state.canvas:show()")
A("        return")
A("    end")
A("    if step <= 7 then")
A("        hs.eventtap.scrollWheel({ 0, -3 }, {})")
A("        hs.timer.doAfter(0.25, function() runStep(state, step + 1) end)")
A("    elseif step == 8 then")
A("        hs.timer.doAfter(0.5, function()")
A("            doClick(state)")
A("            hs.timer.doAfter(0.3, function()")
A("                doClick(state)")
A("            end)")
A("        end)")
A("    end")
A("end")
A("")
A("-- ============================================================")
A("-- Run toggle")
A("-- ============================================================")
A("")
A("local function toggleRun(state)")
A("    if state.running then")
A("        state.running = false")
A("        if state.timer then state.timer:stop(); state.timer = nil end")
A("        redraw(state)")
A('        hs.alert.show("Stop (" .. state.runCount .. " times)", 1)')
A("    else")
A("        state.running = true")
A("        state.runCount = 0")
A("        redraw(state)")
A("        state.timer = hs.timer.doEvery(10, function()")
A("            if not state.running then return end")
A("            runStep(state, 1)")
A("        end)")
A("        state.timer:start()")
A('        hs.alert.show("Start (every 10s: 7 scrolls + click)", 1.5)')
A("    end")
A("end")
A("")
A("local function stopRun(state)")
A("    if state.running then")
A("        state.running = false")
A("        if state.timer then state.timer:stop(); state.timer = nil end")
A("        redraw(state)")
A("    end")
A("end")
A("")
A("-- ============================================================")
A("-- Delete overlay")
A("-- ============================================================")
A("")
A("local function deleteOverlay(state)")
A("    stopRun(state)")
A("    if state.canvas then state.canvas:delete() end")
A("    overlays[state.id] = nil")
A("    local regions = readConfig()")
A("    local newRegions = {}")
A("    for _, r in ipairs(regions) do")
A("        if r.id ~= state.id then table.insert(newRegions, r) end")
A("    end")
A("    writeConfig(newRegions)")
A('    local scName = getScreenName(state.screenIndex)')
A('    hs.alert.show("Deleted from " .. scName, 1)')
A("end")
A("")
A("-- ============================================================")
A("-- Create overlay with screen-aware colors & bounds")
A("-- ============================================================")
A("")
A("local function createOverlay(cfg)")
A("    local w = cfg.width or 120")
A("    local h = cfg.height or 80")
A("    local x = cfg.x or 500")
A("    local y = cfg.y or 400")
A("")
A("    -- Detect which screen this region belongs to")
A("    local cx = x + w / 2")
A("    local cy = y + h / 2")
A("    local scr, scrIdx = getScreenByPos(cx, cy)")
A("    if scrIdx < 0 then scrIdx = 0 end")
A("    local sf = getScreenFrame(scr)")
A("    local sc = getScreenColor(scrIdx)")
A("")
A("    local canvas = hs.canvas.new({ x = x, y = y, w = w, h = h })")
A("    canvas:behavior(hs.canvas.windowBehaviors.canJoinAllSpaces)")
A("    canvas:level(hs.canvas.windowLevels.floating)")
A("    canvas:clickActivating(true)")
A("    canvas:wantsLayer(true)")
A("")
A("    local state = {")
A("        id          = cfg.id,")
A("        canvas      = canvas,")
A("        width       = w,")
A("        height      = h,")
A("        savedX      = x,")
A("        savedY      = y,")
A("        screenIndex = scrIdx,")
A("        screenFrame = sf,")
A("        screenColor = sc,")
A("        running     = false,")
A("        runCount    = 0,")
A("        timer       = nil,")
A("        dragging    = false,")
A("        resizing    = false,")
A("        dragStartX  = 0,")
A("        dragStartY  = 0,")
A("        _dragTimer  = nil,")
A("        closeFrame  = { x = w - 18, y = 2, w = 16, h = 16 },")
A("        btnFrame    = { x = math.floor((w - 64) / 2), y = h - 26, w = 64, h = 22 },")
A("    }")
A("")
A("    redraw(state)")
A("")
A("    canvas:canvasMouseEvents(true, true)")
A("")
A("    canvas:mouseCallback(function(c, msg)")
A('        if type(msg) ~= "string" then return false end')
A("")
A("        local pos = hs.mouse.getAbsolutePosition()")
A("        local mx = pos.x - state.savedX")
A("        local my = pos.y - state.savedY")
A("")
A('        if msg == "mouseDown" then')
A("            -- Close button")
A("            local cf = state.closeFrame")
A("            if pointInRect(mx, my, cf.x, cf.y, cf.w, cf.h) then")
A("                deleteOverlay(state)")
A("                return true")
A("            end")
A("")
A("            -- Start/Stop button")
A("            local bf = state.btnFrame")
A("            if pointInRect(mx, my, bf.x, bf.y, bf.w, bf.h) then")
A("                toggleRun(state)")
A("                return true")
A("            end")
A("        end")
A("")
A('        if editMode and msg == "mouseDown" then')
A("            if pointInRect(mx, my, state.width - 16, state.height - 16, 16, 16) then")
A("                state.resizing = true")
A("            else")
A("                state.dragging = true")
A("            end")
A("            state.dragStartX = pos.x")
A("            state.dragStartY = pos.y")
A("")
A("            if state._dragTimer == nil then")
A("                state._dragTimer = hs.timer.doEvery(0.05, function()")
A("                    if not state.dragging and not state.resizing then")
A("                        state._dragTimer:stop()")
A("                        state._dragTimer = nil")
A("                        return")
A("                    end")
A("                    local cur = hs.mouse.getAbsolutePosition()")
A("                    local dx = cur.x - state.dragStartX")
A("                    local dy = cur.y - state.dragStartY")
A("                    if dx == 0 and dy == 0 then return end")
A("                    state.dragStartX = cur.x")
A("                    state.dragStartY = cur.y")
A("")
A("                    if state.resizing then")
A("                        state.width = math.max(50, state.width + dx)")
A("                        state.height = math.max(30, state.height + dy)")
A("                        state.canvas:frame({ x = state.savedX, y = state.savedY, w = state.width, h = state.height })")
A("                        state.closeFrame = { x = state.width - 18, y = 2, w = 16, h = 16 }")
A("                        state.btnFrame = { x = math.floor((state.width - 64) / 2), y = state.height - 26, w = 64, h = 22 }")
A("                        redraw(state)")
A("                    elseif state.dragging then")
A("                        -- Move with screen bounds constraint")
A("                        local sf = state.screenFrame")
A("                        local newX = state.savedX + dx")
A("                        local newY = state.savedY + dy")
A("                        -- Clamp to screen bounds (keep at least 10px margin)")
A("                        newX = math.max(sf.x + 10, math.min(sf.x + sf.w - state.width - 10, newX))")
A("                        newY = math.max(sf.y + 10, math.min(sf.y + sf.h - state.height - 10, newY))")
A("                        state.savedX = newX")
A("                        state.savedY = newY")
A("                        state.canvas:topLeft({ x = state.savedX, y = state.savedY })")
A("                    end")
A("                end)")
A("                state._dragTimer:start()")
A("            end")
A("            return true")
A("        end")
A("")
A('        if msg == "mouseUp" and (state.dragging or state.resizing) then')
A("            -- Re-detect screen after move/resize")
A("            local newCx = state.savedX + state.width / 2")
A("            local newCy = state.savedY + state.height / 2")
A("            local newScr, newIdx = getScreenByPos(newCx, newCy)")
A("            if newIdx >= 0 and newIdx ~= state.screenIndex then")
A("                state.screenIndex = newIdx")
A("                state.screenFrame = getScreenFrame(newScr)")
A("                state.screenColor = getScreenColor(newIdx)")
A("                redraw(state)")
A("            end")
A("")
A("            local regions = readConfig()")
A("            for _, r in ipairs(regions) do")
A("                if r.id == state.id then")
A("                    r.x = state.savedX")
A("                    r.y = state.savedY")
A("                    r.width = state.width")
A("                    r.height = state.height")
A("                end")
A("            end")
A("            writeConfig(regions)")
A("            state.dragging = false")
A("            state.resizing = false")
A("            if state._dragTimer then")
A("                state._dragTimer:stop()")
A("                state._dragTimer = nil")
A("            end")
A("            return true")
A("        end")
A("")
A("        return false")
A("    end)")
A("")
A("    canvas:show()")
A("    overlays[cfg.id] = state")
A("    return state")
A("end")
A("")
A("-- ============================================================")
A("-- Load / reload all regions")
A("-- ============================================================")
A("")
A("local function loadAll()")
A("    for _, state in pairs(overlays) do")
A("        stopRun(state)")
A("        state.canvas:delete()")
A("    end")
A("    overlays = {}")
A("    local regions = readConfig()")
A("    for _, cfg in ipairs(regions) do")
A("        if cfg.enabled ~= false then")
A("            createOverlay(cfg)")
A("        end")
A("    end")
A('    hs.alert.show("Loaded " .. #regions .. " regions across " .. #hs.screen.allScreens() .. " screens", 1)')
A("end")
A("")
A("local function stopAll()")
A("    for _, state in pairs(overlays) do stopRun(state) end")
A('    hs.alert.show("All stopped", 1)')
A("end")
A("")
A("-- ============================================================")
A("-- New region at mouse cursor (auto-detect screen)")
A("-- ============================================================")
A("")
A("local function genId()")
A('    return "region-" .. tostring(os.time()) .. "-" .. tostring(math.random(1000, 9999))')
A("end")
A("")
A("local function newRegion()")
A("    local pos = hs.mouse.getAbsolutePosition()")
A("    local id = genId()")
A("    local cfg = {")
A("        id = id,")
A("        x = math.max(0, pos.x - 75),")
A("        y = math.max(0, pos.y - 50),")
A("        width = 150,")
A("        height = 100,")
A("        enabled = true,")
A('        color = "#FF4444",')
A("    }")
A("    local regions = readConfig()")
A("    table.insert(regions, cfg)")
A("    writeConfig(regions)")
A("    local _, scrIdx = getScreenByPos(pos.x, pos.y)")
A("    local scName = getScreenName(scrIdx)")
A("    createOverlay(cfg)")
A('    hs.alert.show("New region on " .. scName, 1)')
A("end")
A("")
A("local function clearAllRegions()")
A("    for _, state in pairs(overlays) do")
A("        stopRun(state)")
A("        state.canvas:delete()")
A("    end")
A("    overlays = {}")
A("    writeConfig({})")
A('    hs.alert.show("Cleared all regions", 1)')
A("end")
A("")
A("-- ============================================================")
A("-- Utility: restart an app by bundle ID")
A("-- ============================================================")
A("")
A("local function restartApp(bundleID)")
A("    local app = hs.application.get(bundleID)")
A("    if app then")
A("        app:kill()")
A("        hs.timer.doAfter(1, function()")
A("            hs.application.launchOrFocusByBundleID(bundleID)")
A('            hs.alert.show("Restarted: " .. (app:name() or bundleID), 1.5)')
A("        end)")
A("    else")
A("        hs.application.launchOrFocusByBundleID(bundleID)")
A('        hs.alert.show("Launched: " .. bundleID, 1.5)')
A("    end")
A("end")
A("")
A("-- ============================================================")
A("-- Menu bar")
A("-- ============================================================")
A("")
A("local menu = hs.menubar.new()")
A('menu:setTitle("Region")')
A("")
A("local function buildMenu()")
A("    local regionCount = 0")
A("    for _ in pairs(overlays) do regionCount = regionCount + 1 end")
A("")
A("    -- Count regions per screen")
A("    local perScreen = {}")
A("    for _, st in pairs(overlays) do")
A("        local idx = st.screenIndex")
A("        perScreen[idx] = (perScreen[idx] or 0) + 1")
A("    end")
A("    local screenInfo = {}")
A("    for idx, cnt in pairs(perScreen) do")
A("        table.insert(screenInfo, getScreenName(idx) .. ': ' .. cnt)")
A("    end")
A("    local detail = ''")
A("    if #screenInfo > 0 then")
A("        detail = ' (' .. table.concat(screenInfo, ', ') .. ')'")
A("    end")
A("")
A("    local items = {")
A('        { title = "New region", fn = newRegion },')
A('        { title = "Reload", fn = loadAll },')
A('        { title = "-" },')
A('        { title = "Edit mode: " .. (editMode and "ON" or "OFF"), fn = function()')
A("            editMode = not editMode")
A("            if not editMode then")
A("                for _, st in pairs(overlays) do")
A("                    st.dragging = false")
A("                    st.resizing = false")
A("                    if st._dragTimer then st._dragTimer:stop(); st._dragTimer = nil end")
A("                end")
A("            end")
A("            buildMenu()")
A("        end },")
A('        { title = "-" },')
A('        { title = "Restart", menu = {')
A('            { title = "Restart VS Code", fn = function() restartApp("com.microsoft.VSCode") end },')
A('            { title = "Restart AIoT IDE", fn = function() restartApp("com.aiot.ide") end },')
A('        } },')
A('        { title = "-" },')
A('        { title = "Stop all", fn = stopAll },')
A('        { title = "Clear all regions", fn = clearAllRegions },')
A('        { title = "-" },')
A('        { title = "Loaded: " .. regionCount .. " regions" .. detail, disabled = true },')
A("    }")
A("    menu:setMenu(items)")
A("end")
A("buildMenu()")
A("")
A("loadAll()")
A("")
A("hs.shutdownCallback = function() stopAll() end")
A("")

content = "\n".join(lines)
with open('/Users/Banner/.hammerspoon/init.lua', 'w') as f:
    f.write(content)
print("Written " + str(len(lines)) + " lines")