#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json

lines = []
lines.append("-- ============================================================")
lines.append("-- Region Manager - Hammerspoon v2.0.3")
lines.append("-- ============================================================")
lines.append("")
lines.append('local ok, err = pcall(function() hs.ipc.cliInstall() end)')
lines.append("")
lines.append('local CONFIG_FILE = os.getenv("HOME") .. "/.screen_regions.json"')
lines.append("")
lines.append("local overlays = {}")
lines.append("local editMode = false")
lines.append("")
lines.append("local COLORS = {")
lines.append("    red      = { red = 1.0, green = 0.27, blue = 0.27, alpha = 0.9 },")
lines.append("    green    = { red = 0.13, green = 0.55, blue = 0.13, alpha = 0.9 },")
lines.append("    running  = { red = 0.85, green = 0.20, blue = 0.20, alpha = 0.9 },")
lines.append("    border   = { red = 1.0, green = 0.27, blue = 0.27, alpha = 1.0 },")
lines.append("    fill     = { red = 1.0, green = 1.0, blue = 1.0, alpha = 0.08 },")
lines.append("    white    = { white = 1.0, alpha = 1.0 },")
lines.append("}")
lines.append("")
lines.append("local function readConfig()")
lines.append('    local f = io.open(CONFIG_FILE, "r")')
lines.append("    if not f then return {} end")
lines.append('    local content = f:read("*all")')
lines.append("    f:close()")
lines.append("    local ok, data = pcall(hs.json.decode, content)")
lines.append("    if not ok then return {} end")
lines.append("    return data.regions or {}")
lines.append("end")
lines.append("")
lines.append("local function writeConfig(regions)")
lines.append('    local data = { version = "1.0", regions = regions }')
lines.append('    local f = io.open(CONFIG_FILE, "w")')
lines.append("    if not f then return end")
lines.append("    f:write(hs.json.encode(data))")
lines.append("    f:close()")
lines.append("end")
lines.append("")
lines.append("local function pointInRect(px, py, rx, ry, rw, rh)")
lines.append("    return px >= rx and px <= rx + rw and py >= ry and py <= ry + rh")
lines.append("end")
lines.append("")
lines.append("local function redraw(state)")
lines.append("    local w = state.width")
lines.append("    local h = state.height")
lines.append('    state.canvas[1] = { type = "rectangle", action = "fill", fillColor = COLORS.fill, frame = { x = 0, y = 0, w = w, h = h }, roundedRectRadii = { xRadius = 8, yRadius = 8 } }')
lines.append('    state.canvas[2] = { type = "rectangle", action = "stroke", strokeColor = COLORS.border, strokeWidth = 2, frame = { x = 1, y = 1, w = w - 2, h = h - 2 }, roundedRectRadii = { xRadius = 8, yRadius = 8 } }')
lines.append("    local cx = w - 18")
lines.append("    local cy = 2")
lines.append('    state.canvas[3] = { type = "rectangle", action = "fill", fillColor = COLORS.red, frame = { x = cx, y = cy, w = 16, h = 16 }, roundedRectRadii = { xRadius = 3, yRadius = 3 } }')
lines.append('    state.canvas[4] = { type = "text", text = "x", textColor = COLORS.white, textSize = 12, textAlignment = "center", frame = { x = cx, y = cy + 1, w = 16, h = 15 } }')
lines.append("    local bw = 64")
lines.append("    local bh = 22")
lines.append("    local bx = math.floor((w - bw) / 2)")
lines.append("    local by = h - bh - 4")
lines.append("    state.btnFrame = { x = bx, y = by, w = bw, h = bh }")
lines.append("    if state.running then")
lines.append('        state.canvas[5] = { type = "rectangle", action = "fill", fillColor = COLORS.running, frame = { x = bx, y = by, w = bw, h = bh }, roundedRectRadii = { xRadius = 4, yRadius = 4 } }')
lines.append('        state.canvas[6] = { type = "text", text = state.runCount .. " times", textColor = COLORS.white, textSize = 9, textAlignment = "center", frame = { x = bx, y = by + 2, w = bw, h = bh - 2 } }')
lines.append("    else")
lines.append('        state.canvas[5] = { type = "rectangle", action = "fill", fillColor = COLORS.green, frame = { x = bx, y = by, w = bw, h = bh }, roundedRectRadii = { xRadius = 4, yRadius = 4 } }')
lines.append('        state.canvas[6] = { type = "text", text = "Start", textColor = COLORS.white, textSize = 10, textAlignment = "center", frame = { x = bx, y = by + 2, w = bw, h = bh - 2 } }')
lines.append("    end")
lines.append("end")
lines.append("")
lines.append("local function doClick(state)")
lines.append("    local cx = state.savedX + state.width / 2")
lines.append("    local cy = state.savedY + state.height / 2")
lines.append("    state.canvas:hide()")
lines.append("    hs.timer.doAfter(0.08, function()")
lines.append("        hs.eventtap.leftClick({ x = cx, y = cy })")
lines.append("        hs.timer.doAfter(0.15, function()")
lines.append("            state.canvas:show()")
lines.append("            if state.running then")
lines.append("                state.runCount = state.runCount + 1")
lines.append("                if state.canvas and state.canvas[6] then")
lines.append('                    state.canvas[6].text = state.runCount .. " times"')
lines.append("                end")
lines.append("            end")
lines.append("        end)")
lines.append("    end)")
lines.append("end")
lines.append("")
lines.append("local function runStep(state, step)")
lines.append("    if not state.running then")
lines.append("        state.canvas:show()")
lines.append("        return")
lines.append("    end")
lines.append("    if step <= 7 then")
lines.append("        hs.eventtap.scrollWheel({ 0, -3 }, {})")
lines.append("        hs.timer.doAfter(0.25, function() runStep(state, step + 1) end)")
lines.append("    elseif step == 8 then")
lines.append("        hs.timer.doAfter(0.5, function()")
lines.append("            doClick(state)")
lines.append("            hs.timer.doAfter(0.3, function()")
lines.append("                doClick(state)")
lines.append("            end)")
lines.append("        end)")
lines.append("    end")
lines.append("end")
lines.append("")
lines.append("local function toggleRun(state)")
lines.append("    if state.running then")
lines.append("        state.running = false")
lines.append("        if state.timer then state.timer:stop(); state.timer = nil end")
lines.append("        redraw(state)")
lines.append('        hs.alert.show("Stop (" .. state.runCount .. " times)", 1)')
lines.append("    else")
lines.append("        state.running = true")
lines.append("        state.runCount = 0")
lines.append("        redraw(state)")
lines.append("        state.timer = hs.timer.doEvery(10, function()")
lines.append("            if not state.running then return end")
lines.append("            runStep(state, 1)")
lines.append("        end)")
lines.append("        state.timer:start()")
lines.append('        hs.alert.show("Start (every 10s: 7 scrolls + click)", 1.5)')
lines.append("    end")
lines.append("end")
lines.append("")
lines.append("local function stopRun(state)")
lines.append("    if state.running then")
lines.append("        state.running = false")
lines.append("        if state.timer then state.timer:stop(); state.timer = nil end")
lines.append("        redraw(state)")
lines.append("    end")
lines.append("end")
lines.append("")
lines.append("local function deleteOverlay(state)")
lines.append("    stopRun(state)")
lines.append("    if state.canvas then state.canvas:delete() end")
lines.append("    overlays[state.id] = nil")
lines.append("    local regions = readConfig()")
lines.append("    local newRegions = {}")
lines.append("    for _, r in ipairs(regions) do")
lines.append("        if r.id ~= state.id then table.insert(newRegions, r) end")
lines.append("    end")
lines.append("    writeConfig(newRegions)")
lines.append('    hs.alert.show("deleted", 1)')
lines.append("end")
lines.append("")
lines.append("local function createOverlay(cfg)")
lines.append("    local w = cfg.width or 120")
lines.append("    local h = cfg.height or 80")
lines.append("    local x = cfg.x or 500")
lines.append("    local y = cfg.y or 400")
lines.append("")
lines.append("    local canvas = hs.canvas.new({ x = x, y = y, w = w, h = h })")
lines.append("    canvas:behavior(hs.canvas.windowBehaviors.canJoinAllSpaces)")
lines.append("    canvas:level(hs.canvas.windowLevels.floating)")
lines.append("    canvas:clickActivating(true)")
lines.append("    canvas:wantsLayer(true)")
lines.append("")
lines.append("    local state = {")
lines.append("        id = cfg.id,")
lines.append("        canvas = canvas,")
lines.append("        width = w,")
lines.append("        height = h,")
lines.append("        savedX = x,")
lines.append("        savedY = y,")
lines.append("        running = false,")
lines.append("        runCount = 0,")
lines.append("        timer = nil,")
lines.append("        dragging = false,")
lines.append("        resizing = false,")
lines.append("        dragStartX = 0,")
lines.append("        dragStartY = 0,")
lines.append("        _dragTimer = nil,")
lines.append("        closeFrame = { x = w - 18, y = 2, w = 16, h = 16 },")
lines.append("        btnFrame = { x = math.floor((w - 64) / 2), y = h - 26, w = 64, h = 22 },")
lines.append("    }")
lines.append("")
lines.append("    redraw(state)")
lines.append("")
lines.append("    canvas:canvasMouseEvents(true, true)")
lines.append("")
lines.append("    canvas:mouseCallback(function(c, msg)")
lines.append('        if type(msg) ~= "string" then return false end')
lines.append("")
lines.append("        local pos = hs.mouse.getAbsolutePosition()")
lines.append("        local mx = pos.x - state.savedX")
lines.append("        local my = pos.y - state.savedY")
lines.append("")
lines.append('        if msg == "mouseDown" then')
lines.append("            local cf = state.closeFrame")
lines.append("            if pointInRect(mx, my, cf.x, cf.y, cf.w, cf.h) then")
lines.append("                deleteOverlay(state)")
lines.append("                return true")
lines.append("            end")
lines.append("")
lines.append("            local bf = state.btnFrame")
lines.append("            if pointInRect(mx, my, bf.x, bf.y, bf.w, bf.h) then")
lines.append("                toggleRun(state)")
lines.append("                return true")
lines.append("            end")
lines.append("        end")
lines.append("")
lines.append('        if editMode and msg == "mouseDown" then')
lines.append("            if pointInRect(mx, my, state.width - 16, state.height - 16, 16, 16) then")
lines.append("                state.resizing = true")
lines.append("            else")
lines.append("                state.dragging = true")
lines.append("            end")
lines.append("            state.dragStartX = pos.x")
lines.append("            state.dragStartY = pos.y")
lines.append("")
lines.append("            if state._dragTimer == nil then")
lines.append("                state._dragTimer = hs.timer.doEvery(0.05, function()")
lines.append("                    if not state.dragging and not state.resizing then")
lines.append("                        state._dragTimer:stop()")
lines.append("                        state._dragTimer = nil")
lines.append("                        return")
lines.append("                    end")
lines.append("                    local cur = hs.mouse.getAbsolutePosition()")
lines.append("                    local dx = cur.x - state.dragStartX")
lines.append("                    local dy = cur.y - state.dragStartY")
lines.append("                    if dx == 0 and dy == 0 then return end")
lines.append("                    state.dragStartX = cur.x")
lines.append("                    state.dragStartY = cur.y")
lines.append("")
lines.append("                    if state.resizing then")
lines.append("                        state.width = math.max(50, state.width + dx)")
lines.append("                        state.height = math.max(30, state.height + dy)")
lines.append("                        state.canvas:frame({ x = state.savedX, y = state.savedY, w = state.width, h = state.height })")
lines.append("                        state.closeFrame = { x = state.width - 18, y = 2, w = 16, h = 16 }")
lines.append("                        state.btnFrame = { x = math.floor((state.width - 64) / 2), y = state.height - 26, w = 64, h = 22 }")
lines.append("                        redraw(state)")
lines.append("                    elseif state.dragging then")
lines.append("                        state.savedX = state.savedX + dx")
lines.append("                        state.savedY = state.savedY + dy")
lines.append("                        state.canvas:topLeft({ x = state.savedX, y = state.savedY })")
lines.append("                    end")
lines.append("                end)")
lines.append("                state._dragTimer:start()")
lines.append("            end")
lines.append("            return true")
lines.append("        end")
lines.append("")
lines.append('        if msg == "mouseUp" and (state.dragging or state.resizing) then')
lines.append("            local regions = readConfig()")
lines.append("            for _, r in ipairs(regions) do")
lines.append("                if r.id == state.id then")
lines.append("                    r.x = state.savedX")
lines.append("                    r.y = state.savedY")
lines.append("                    r.width = state.width")
lines.append("                    r.height = state.height")
lines.append("                end")
lines.append("            end")
lines.append("            writeConfig(regions)")
lines.append("            state.dragging = false")
lines.append("            state.resizing = false")
lines.append("            if state._dragTimer then")
lines.append("                state._dragTimer:stop()")
lines.append("                state._dragTimer = nil")
lines.append("            end")
lines.append("            return true")
lines.append("        end")
lines.append("")
lines.append("        return false")
lines.append("    end)")
lines.append("")
lines.append("    canvas:show()")
lines.append("    overlays[cfg.id] = state")
lines.append("    return state")
lines.append("end")
lines.append("")
lines.append("local function loadAll()")
lines.append("    for _, state in pairs(overlays) do")
lines.append("        stopRun(state)")
lines.append("        state.canvas:delete()")
lines.append("    end")
lines.append("    overlays = {}")
lines.append("    local regions = readConfig()")
lines.append("    for _, cfg in ipairs(regions) do")
lines.append("        if cfg.enabled ~= false then")
lines.append("            createOverlay(cfg)")
lines.append("        end")
lines.append("    end")
lines.append('    hs.alert.show("\u5df2\u52a0\u8f7d " .. #regions .. " \u4e2a\u533a\u57df", 1)')
lines.append("end")
lines.append("")
lines.append("local function stopAll()")
lines.append("    for _, state in pairs(overlays) do stopRun(state) end")
lines.append('    hs.alert.show("\u5168\u90e8\u505c\u6b62", 1)')
lines.append("end")
lines.append("")
lines.append("local function genId()")
lines.append('    return "region-" .. tostring(os.time()) .. "-" .. tostring(math.random(1000, 9999))')
lines.append("end")
lines.append("")
lines.append("local function newRegion()")
lines.append("    local pos = hs.mouse.getAbsolutePosition()")
lines.append("    local id = genId()")
lines.append("    local cfg = {")
lines.append("        id = id,")
lines.append("        x = math.max(0, pos.x - 75),")
lines.append("        y = math.max(0, pos.y - 50),")
lines.append("        width = 150,")
lines.append("        height = 100,")
lines.append("        enabled = true,")
lines.append('        color = "#FF4444",')
lines.append("    }")
lines.append("    local regions = readConfig()")
lines.append("    table.insert(regions, cfg)")
lines.append("    writeConfig(regions)")
lines.append("    createOverlay(cfg)")
lines.append('    hs.alert.show("\u65b0\u5efa\u533a\u57df: " .. id, 1)')
lines.append("end")
lines.append("")
lines.append("local function clearAllRegions()")
lines.append("    for _, state in pairs(overlays) do")
lines.append("        stopRun(state)")
lines.append("        state.canvas:delete()")
lines.append("    end")
lines.append("    overlays = {}")
lines.append("    writeConfig({})")
lines.append('    hs.alert.show("\u5df2\u6e05\u9664\u6240\u6709\u533a\u57df", 1)')
lines.append("end")
lines.append("")
lines.append("local menu = hs.menubar.new()")
lines.append('menu:setTitle("\u533a\u57df")')
lines.append("")
lines.append("local function buildMenu()")
lines.append("    local regionCount = 0")
lines.append("    for _ in pairs(overlays) do regionCount = regionCount + 1 end")
lines.append("")
lines.append("    local items = {")
lines.append('        { title = "\u65b0\u5efa\u533a\u57df", fn = newRegion },')
lines.append('        { title = "\u91cd\u65b0\u52a0\u8f7d", fn = loadAll },')
lines.append('        { title = "-" },')
lines.append('        { title = "\u7f16\u8f91\u6a21\u5f0f: " .. (editMode and "\u5f00" or "\u5173"), fn = function()')
lines.append("            editMode = not editMode")
lines.append("            if not editMode then")
lines.append("                for _, st in pairs(overlays) do")
lines.append("                    st.dragging = false")
lines.append("                    st.resizing = false")
lines.append("                    if st._dragTimer then st._dragTimer:stop(); st._dragTimer = nil end")
lines.append("                end")
lines.append("            end")
lines.append("            buildMenu()")
lines.append("        end },")
lines.append('        { title = "-" },')
lines.append('        { title = "\u5168\u90e8\u505c\u6b62", fn = stopAll },')
lines.append('        { title = "\u6e05\u9664\u6240\u6709\u533a\u57df", fn = clearAllRegions },')
lines.append('        { title = "-" },')
lines.append('        { title = "\u5df2\u52a0\u8f7d: " .. regionCount .. " \u4e2a", disabled = true },')
lines.append("    }")
lines.append("    menu:setMenu(items)")
lines.append("end")
lines.append("buildMenu()")
lines.append("")
lines.append("loadAll()")
lines.append("")
lines.append("hs.shutdownCallback = function() stopAll() end")
lines.append("")

content = "\n".join(lines)
with open('/Users/Banner/.hammerspoon/init.lua', 'w') as f:
    f.write(content)
print("Written " + str(len(lines)) + " lines")