// lib/notify.js - Email notification for activation events
// Supports Resend API (default) and SMTP fallback
// Resend: https://resend.com - ev.mail.gudq.com verified

var https = require("https");
var tls = require("tls");

var EMAIL_PROVIDER = process.env.EMAIL_PROVIDER || "resend";
var RESEND_API_KEY = process.env.RESEND_API_KEY || "";
var RESEND_FROM = process.env.RESEND_FROM || "app-auth <notify@ev.mail.gudq.com>";

var SMTP_HOST = process.env.SMTP_HOST || "smtp.qq.com";
var SMTP_PORT = parseInt(process.env.SMTP_PORT || "465", 10);
var SMTP_USER = process.env.SMTP_USER || "rinuo@qq.com";
var SMTP_PASS = process.env.SMTP_PASS || "";
var NOTIFY_TO = process.env.NOTIFY_TO || "rinuo@qq.com";
var NOTIFY_FROM_NAME = process.env.NOTIFY_FROM_NAME || "app-auth";

var EMAIL_LOG_KEY = "auth:email_logs";
var EMAIL_LOG_MAX = 100;

function getRedis() {
  try {
    return require("./redis");
  } catch (e) {
    return null;
  }
}

function escapeHtml(str) {
  if (!str) return "";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function parseUserAgent(ua) {
  if (!ua) return "Unknown";
  var os = "Unknown";
  if (/Windows/i.test(ua)) os = "Windows";
  else if (/Mac/i.test(ua) || /Macintosh/i.test(ua)) os = "macOS";
  else if (/Linux/i.test(ua) && !/Android/i.test(ua)) os = "Linux";
  else if (/Android/i.test(ua)) os = "Android";
  else if (/iPhone|iPad|iOS/i.test(ua)) os = "iOS";

  var browser = "Unknown";
  if (/Edg\//i.test(ua)) browser = "Edge";
  else if (/Chrome/i.test(ua) && !/Edg\//i.test(ua)) browser = "Chrome";
  else if (/Safari/i.test(ua)) browser = "Safari";
  else if (/Firefox/i.test(ua)) browser = "Firefox";
  else if (/OPR/i.test(ua)) browser = "Opera";

  var device = "Desktop";
  if (/Mobi|Android|iPhone|iPad/i.test(ua)) device = "Mobile";

  return { os: os, browser: browser, device: device, raw: ua };
}

function collectRequestInfo(req) {
  var headers = req.headers || {};
  var ua = parseUserAgent(headers["user-agent"] || "");

  var ip = headers["x-real-ip"] ||
    headers["x-forwarded-for"] ||
    (req.connection && req.connection.remoteAddress) ||
    (req.socket && req.socket.remoteAddress) ||
    "Unknown";

  if (ip && ip.indexOf(",") > -1) {
    ip = ip.split(",")[0].trim();
  }

  return {
    ip: ip,
    userAgent: ua.raw,
    os: ua.os,
    browser: ua.browser,
    device: ua.device,
    referer: headers["referer"] || headers["referrer"] || "",
    origin: headers["origin"] || "",
    host: headers["host"] || "",
    language: headers["accept-language"] || "",
    time: new Date().toISOString(),
  };
}

function buildHtmlEmail(info, activationResult) {
  var rows = [
    ["Time", info.time],
    ["IP Address", info.ip],
    ["OS", info.os],
    ["Browser", info.browser],
    ["Device", info.device],
    ["Referer", info.referer || "(direct)"],
    ["Origin", info.origin || "-"],
    ["Host", info.host || "-"],
    ["Language", info.language || "-"],
    ["", ""],
    ["Redeem Code", activationResult.redeemCode || "-"],
    ["Product ID", activationResult.productId || "-"],
    ["Device ID", activationResult.deviceId || "-"],
    ["Months", activationResult.months || "-"],
    ["Activation Code", activationResult.activationCode || "-"],
  ];

  if (activationResult.source) {
    rows.push(["Source", activationResult.source]);
  }

  if (activationResult.deviceInfo) {
    var di = activationResult.deviceInfo;
    rows.push(["", ""]);
    rows.push(["Device Info", ""]);
    if (di.model) rows.push(["  Model", escapeHtml(di.model)]);
    if (di.product) rows.push(["  Product", escapeHtml(di.product)]);
    if (di.osVersionCode) rows.push(["  OS Version", escapeHtml(di.osVersionCode)]);
    if (di.platformVersionCode) rows.push(["  Platform", escapeHtml(di.platformVersionCode)]);
    if (di.deviceType) rows.push(["  Type", escapeHtml(di.deviceType)]);
    if (di.screenShape) {
      var screenInfo = di.screenShape;
      if (di.screenWidth && di.screenHeight) screenInfo += " (" + di.screenWidth + "x" + di.screenHeight + ")";
      rows.push(["  Screen", escapeHtml(screenInfo)]);
    }
    if (di.apiLevel) rows.push(["  API Level", escapeHtml(di.apiLevel)]);
    if (di.language) rows.push(["  Language", escapeHtml(di.language)]);
  }

  var rowHtml = rows.map(function (r) {
    return "<tr><td style='padding:4px 12px 4px 0;color:#64748b;white-space:nowrap;vertical-align:top'>" +
      r[0] + "</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>" + r[1] + "</td></tr>";
  }).join("");

  return "<div style='font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px'>" +
    "<h2 style='color:#1e293b;border-bottom:2px solid #3b82f6;padding-bottom:8px'>New Activation</h2>" +
    "<table style='border-collapse:collapse;width:100%'>" + rowHtml + "</table>" +
    "<p style='color:#94a3b8;font-size:12px;margin-top:20px'>Auto-generated by app-auth system</p>" +
    "</div>";
}

function buildTextEmail(info, activationResult) {
  var lines = [
    "New Activation",
    "==============",
    "",
    "Time: " + info.time,
    "IP: " + info.ip,
    "OS: " + info.os,
    "Browser: " + info.browser,
    "Device: " + info.device,
    "Referer: " + (info.referer || "(direct)"),
    "Origin: " + (info.origin || "-"),
    "Host: " + (info.host || "-"),
    "Language: " + (info.language || "-"),
    "",
    "Redeem Code: " + (activationResult.redeemCode || "-"),
    "Product ID: " + (activationResult.productId || "-"),
    "Device ID: " + (activationResult.deviceId || "-"),
    "Months: " + (activationResult.months || "-"),
    "Activation Code: " + (activationResult.activationCode || "-"),
  ];
  if (activationResult.source) {
    lines.push("Source: " + activationResult.source);
  }
  if (activationResult.deviceInfo) {
    var di = activationResult.deviceInfo;
    lines.push("");
    lines.push("Device Info:");
    if (di.model) lines.push("  Model: " + di.model);
    if (di.product) lines.push("  Product: " + di.product);
    if (di.osVersionCode) lines.push("  OS Version: " + di.osVersionCode);
    if (di.platformVersionCode) lines.push("  Platform: " + di.platformVersionCode);
    if (di.deviceType) lines.push("  Type: " + di.deviceType);
    if (di.screenShape) {
      var screenInfo = di.screenShape;
      if (di.screenWidth && di.screenHeight) screenInfo += " (" + di.screenWidth + "x" + di.screenHeight + ")";
      lines.push("  Screen: " + screenInfo);
    }
    if (di.apiLevel) lines.push("  API Level: " + di.apiLevel);
    if (di.language) lines.push("  Language: " + di.language);
  }
  return lines.join("\n");
}

function base64(str) {
  return Buffer.from(str, "utf-8").toString("base64");
}

function buildEmailContent(fromAddr, toAddr, subject, htmlBody, textBody) {
  var boundary = "==boundary_" + Date.now() + "_" + Math.random().toString(36).slice(2);
  var lines = [
    "From: " + fromAddr,
    "To: " + toAddr,
    "Subject: =?UTF-8?B?" + base64(subject) + "?=",
    "MIME-Version: 1.0",
    "Content-Type: multipart/alternative; boundary=\"" + boundary + "\"",
    "",
    "--" + boundary,
    "Content-Type: text/plain; charset=UTF-8",
    "Content-Transfer-Encoding: base64",
    "",
  ];

  var textLines = textBody.split("\n");
  for (var i = 0; i < textLines.length; i++) {
    lines.push(base64(textLines[i] + "\r\n"));
  }

  lines.push("");
  lines.push("--" + boundary);
  lines.push("Content-Type: text/html; charset=UTF-8");
  lines.push("Content-Transfer-Encoding: base64");
  lines.push("");

  var htmlLines = htmlBody.split("\n");
  for (var j = 0; j < htmlLines.length; j++) {
    lines.push(base64(htmlLines[j] + "\r\n"));
  }

  lines.push("");
  lines.push("--" + boundary + "--");
  lines.push(".");

  return lines.join("\r\n");
}

function smtpCommand(socket, cmd) {
  return new Promise(function (resolve, reject) {
    var onData = function (data) {
      var text = data.toString();
      socket.removeListener("data", onData);
      resolve(text);
    };
    socket.on("data", onData);
    socket.write(cmd + "\r\n");
  });
}

async function sendViaSMTP(fromAddr, toAddr, subject, htmlBody, textBody) {
  return new Promise(function (resolve, reject) {
    var socket = tls.connect({
      host: SMTP_HOST,
      port: SMTP_PORT,
      rejectUnauthorized: false,
      timeout: 15000,
    }, async function () {
      try {
        var greeting = await smtpCommand(socket, "");
        console.log("[notify] SMTP greeting:", greeting.substring(0, 100).trim());

        await smtpCommand(socket, "EHLO app-auth");
        await smtpCommand(socket, "AUTH LOGIN");
        await smtpCommand(socket, base64(SMTP_USER));
        await smtpCommand(socket, base64(SMTP_PASS));

        await smtpCommand(socket, "MAIL FROM:<" + SMTP_USER + ">");
        await smtpCommand(socket, "RCPT TO:<" + toAddr + ">");

        var content = buildEmailContent(fromAddr, toAddr, subject, htmlBody, textBody);
        await smtpCommand(socket, "DATA");
        var result = await smtpCommand(socket, content);

        await smtpCommand(socket, "QUIT");

        console.log("[notify] SMTP send result:", result.substring(0, 100).trim());
        socket.end();
        resolve(true);
      } catch (e) {
        console.error("[notify] SMTP error:", e.message);
        try { socket.end(); } catch (_) {}
        resolve(false);
      }
    });

    socket.on("error", function (e) {
      console.error("[notify] SMTP connection error:", e.message);
      resolve(false);
    });

    socket.on("timeout", function () {
      console.error("[notify] SMTP connection timeout");
      try { socket.destroy(); } catch (_) {}
      resolve(false);
    });
  });
}

async function sendViaResend(fromAddr, toAddr, subject, htmlBody, textBody) {
  if (!RESEND_API_KEY) {
    throw new Error("RESEND_API_KEY not configured");
  }

  var body = JSON.stringify({
    from: fromAddr,
    to: [toAddr],
    subject: subject,
    html: htmlBody,
    text: textBody,
  });

  return new Promise(function (resolve, reject) {
    var req = https.request({
      hostname: "api.resend.com",
      path: "/emails",
      method: "POST",
      headers: {
        "Authorization": "Bearer " + RESEND_API_KEY,
        "Content-Type": "application/json",
        "Content-Length": Buffer.byteLength(body),
      },
      timeout: 10000,
    }, function (res) {
      var data = "";
      res.on("data", function (chunk) { data += chunk; });
      res.on("end", function () {
        try {
          var json = JSON.parse(data);
          if (res.statusCode >= 200 && res.statusCode < 300 && json.id) {
            console.log("[notify] Resend OK: id=" + json.id);
            resolve({ id: json.id });
          } else {
            var errMsg = "Resend HTTP " + res.statusCode + ": " + JSON.stringify(json);
            console.error("[notify] Resend failed:", errMsg);
            reject(new Error(errMsg));
          }
        } catch (e) {
          reject(new Error("Resend parse error: " + data.substring(0, 200)));
        }
      });
    });

    req.on("error", function (e) {
      console.error("[notify] Resend request error:", e.message);
      reject(e);
    });

    req.on("timeout", function () {
      req.destroy();
      reject(new Error("Resend request timeout"));
    });

    req.write(body);
    req.end();
  });
}

async function sendEmail(fromAddr, toAddr, subject, htmlBody, textBody) {
  if (EMAIL_PROVIDER === "resend" && RESEND_API_KEY) {
    try {
      return await sendViaResend(fromAddr || RESEND_FROM, toAddr, subject, htmlBody, textBody);
    } catch (e) {
      console.error("[notify] Resend failed, falling back to SMTP:", e.message);
      if (SMTP_PASS) {
        return await sendViaSMTP(fromAddr, toAddr, subject, htmlBody, textBody);
      }
      throw e;
    }
  }

  if (EMAIL_PROVIDER === "smtp" || SMTP_PASS) {
    return await sendViaSMTP(fromAddr, toAddr, subject, htmlBody, textBody);
  }

  throw new Error("No email provider configured");
}

async function logEmailEvent(entry) {
  try {
    var redis = getRedis();
    if (!redis) return;
    var record = JSON.stringify({
      time: new Date().toISOString(),
      type: entry.type || "info",
      to: entry.to || NOTIFY_TO,
      subject: entry.subject || "",
      status: entry.status || "sent",
      error: entry.error || "",
      source: entry.source || "activation",
      visitor: entry.visitor || null,
    });
    await redis.lpush(EMAIL_LOG_KEY, record);
    await redis.ltrim(EMAIL_LOG_KEY, 0, EMAIL_LOG_MAX - 1);
  } catch (e) {
    console.error("[notify] Failed to log email event:", e.message);
  }
}

async function getEmailLogs(limit) {
  try {
    var redis = getRedis();
    if (!redis) return [];
    var lim = Math.min(limit || 50, 200);
    var raw = await redis.lrange(EMAIL_LOG_KEY, 0, lim - 1);
    if (!Array.isArray(raw)) return [];
    return raw.map(function(r) {
      try { return JSON.parse(r); } catch (_) { return null; }
    }).filter(Boolean);
  } catch (e) {
    console.error("[notify] Failed to get email logs:", e.message);
    return [];
  }
}

async function sendActivationNotification(req, activationResult) {
  var info = collectRequestInfo(req);
  var subject = "[Activation] " + (activationResult.productId || "?") +
    " - " + (activationResult.redeemCode || "?") +
    " | " + (info.os || "?") + " " + (info.device || "?");

  var htmlBody = buildHtmlEmail(info, activationResult);
  var textBody = buildTextEmail(info, activationResult);

  var fromAddr = EMAIL_PROVIDER === "resend" ? RESEND_FROM : (NOTIFY_FROM_NAME + " <" + SMTP_USER + ">");
  var provider = EMAIL_PROVIDER;

  if (EMAIL_PROVIDER === "resend" && RESEND_API_KEY) {
    try {
      var result = await sendViaResend(fromAddr, NOTIFY_TO, subject, htmlBody, textBody);
      await logEmailEvent({
        type: "activation",
        to: NOTIFY_TO,
        subject: subject,
        status: "success",
        source: "activation",
        provider: "resend",
        resendId: result && result.id,
        visitor: info,
      });
      console.log("[notify] Activation email sent via Resend: id=" + (result && result.id));
      return { sent: true, provider: "resend", id: result && result.id };
    } catch (e) {
      console.error("[notify] Resend failed, trying SMTP fallback:", e.message);
      if (SMTP_PASS) {
        try {
          var smtpFrom = NOTIFY_FROM_NAME + " <" + SMTP_USER + ">";
          await sendViaSMTP(smtpFrom, NOTIFY_TO, subject, htmlBody, textBody);
          provider = "smtp";
          await logEmailEvent({
            type: "activation",
            to: NOTIFY_TO,
            subject: subject,
            status: "success",
            source: "activation",
            provider: "smtp-fallback",
            visitor: info,
          });
          return { sent: true, provider: "smtp", fallback: true };
        } catch (e2) {
          console.error("[notify] SMTP fallback also failed:", e2.message);
          await logEmailEvent({
            type: "activation",
            to: NOTIFY_TO,
            subject: subject,
            status: "failed",
            error: "Resend: " + e.message + "; SMTP: " + e2.message,
            source: "activation",
            provider: "both-failed",
            visitor: info,
          });
          return { sent: false, error: "Resend: " + e.message + "; SMTP: " + e2.message };
        }
      } else {
        await logEmailEvent({
          type: "activation",
          to: NOTIFY_TO,
          subject: subject,
          status: "failed",
          error: e.message,
          source: "activation",
          provider: "resend",
          visitor: info,
        });
        return { sent: false, error: e.message };
      }
    }
  } else if (SMTP_PASS) {
    try {
      await sendViaSMTP(fromAddr, NOTIFY_TO, subject, htmlBody, textBody);
      await logEmailEvent({
        type: "activation",
        to: NOTIFY_TO,
        subject: subject,
        status: "success",
        source: "activation",
        provider: "smtp",
        visitor: info,
      });
      return { sent: true, provider: "smtp" };
    } catch (e) {
      console.error("[notify] Failed to send email:", e.message);
      await logEmailEvent({
        type: "activation",
        to: NOTIFY_TO,
        subject: subject,
        status: "failed",
        error: e.message,
        source: "activation",
        provider: "smtp",
        visitor: info,
      });
      return { sent: false, error: e.message };
    }
  } else {
    console.log("[notify] No email provider configured, logging instead:");
    console.log("[notify] Subject:", subject);
    console.log("[notify] Body:", textBody);
    await logEmailEvent({
      type: "activation",
      to: NOTIFY_TO,
      subject: subject,
      status: "skipped",
      error: "No email provider configured",
      source: "activation",
      provider: "none",
      visitor: info,
    });
    return { sent: false, error: "No email provider configured" };
  }
}

async function sendTestEmail(options) {
  var provider = options.provider || EMAIL_PROVIDER;
  var to = options.notifyTo || NOTIFY_TO;
  var startTime = Date.now();
  var steps = [];

  function addStep(command, response, ok) {
    steps.push({
      command: command,
      response: (response || "").substring(0, 500).trim(),
      ok: ok !== false,
      time: new Date().toISOString()
    });
  }

  var customSubject = options.customSubject || "";
  var customBody = options.customBody || "";
  var subject = customSubject || "[Test] app-auth Email Notification Test";
  var now = new Date().toISOString();

  if (provider === "resend" && RESEND_API_KEY) {
    var fromAddr = options.resendFrom || RESEND_FROM;
    var config = {
      provider: "resend",
      from: fromAddr,
      to: to,
      time: now,
    };

    var defaultHtmlBody = "<div style='font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px'>" +
      "<h2 style='color:#10b981;border-bottom:2px solid #10b981;padding-bottom:8px'>Email Test Successful</h2>" +
      "<p style='color:#374151;font-size:14px'>This is a test email from the app-auth system via Resend.</p>" +
      "<table style='border-collapse:collapse;width:100%;margin-top:16px'>" +
      "<tr><td style='padding:4px 12px 4px 0;color:#64748b'>Time</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>" + now + "</td></tr>" +
      "<tr><td style='padding:4px 12px 4px 0;color:#64748b'>Provider</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>Resend API</td></tr>" +
      "<tr><td style='padding:4px 12px 4px 0;color:#64748b'>From</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>" + fromAddr + "</td></tr>" +
      "<tr><td style='padding:4px 12px 4px 0;color:#64748b'>To</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>" + to + "</td></tr>" +
      "</table>" +
      "<p style='color:#94a3b8;font-size:12px;margin-top:20px'>If you received this email, your Resend API settings are configured correctly.</p>" +
      "</div>";
    var defaultTextBody = "Email Test Successful\n==================\n\nTime: " + now + "\nProvider: Resend API\nFrom: " + fromAddr + "\nTo: " + to + "\n\nIf you received this email, your Resend API settings are configured correctly.";
    var htmlBody = customBody || defaultHtmlBody;
    var textBody = customBody || defaultTextBody;

    try {
      var result = await sendViaResend(fromAddr, to, subject, htmlBody, textBody);
      addStep("Resend API", "id=" + result.id + " HTTP 200", true);

      await logEmailEvent({
        type: "test",
        to: to,
        subject: subject,
        status: "success",
        source: "test",
        provider: "resend",
      });

      var elapsedMs = Date.now() - startTime;
      return {
        success: true,
        elapsedMs: elapsedMs,
        config: config,
        steps: steps,
        message: "Test email sent via Resend to " + to + " (id=" + result.id + ")",
      };
    } catch (e) {
      addStep("Resend API", "Error: " + e.message, false);

      await logEmailEvent({
        type: "test",
        to: to,
        subject: subject,
        status: "failed",
        error: e.message,
        source: "test",
        provider: "resend",
      });

      var elapsedMs = Date.now() - startTime;
      return {
        success: false,
        elapsedMs: elapsedMs,
        config: config,
        steps: steps,
        error: "Resend error: " + e.message,
      };
    }
  }

  var host = options.smtpHost || SMTP_HOST;
  var port = options.smtpPort || SMTP_PORT;
  var user = options.smtpUser || SMTP_USER;
  var pass = options.smtpPass || SMTP_PASS;
  var fromName = options.notifyFromName || NOTIFY_FROM_NAME;

  var config = {
    provider: "smtp",
    host: host,
    port: port,
    user: user,
    to: to,
    fromName: fromName,
    time: now,
  };

  if (!pass) {
    return {
      success: false,
      elapsedMs: Date.now() - startTime,
      config: config,
      steps: steps,
      error: "SMTP password is not configured"
    };
  }

  var fromAddr = fromName + " <" + user + ">";
  var defaultHtmlBody = "<div style='font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px'>" +
    "<h2 style='color:#10b981;border-bottom:2px solid #10b981;padding-bottom:8px'>Email Test Successful</h2>" +
    "<p style='color:#374151;font-size:14px'>This is a test email from the app-auth system.</p>" +
    "<table style='border-collapse:collapse;width:100%;margin-top:16px'>" +
    "<tr><td style='padding:4px 12px 4px 0;color:#64748b'>Time</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>" + now + "</td></tr>" +
    "<tr><td style='padding:4px 12px 4px 0;color:#64748b'>SMTP Server</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>" + host + ":" + port + "</td></tr>" +
    "<tr><td style='padding:4px 12px 4px 0;color:#64748b'>From</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>" + user + "</td></tr>" +
    "<tr><td style='padding:4px 12px 4px 0;color:#64748b'>To</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>" + to + "</td></tr>" +
    "</table>" +
    "<p style='color:#94a3b8;font-size:12px;margin-top:20px'>If you received this email, your SMTP settings are configured correctly.</p>" +
    "</div>";
  var defaultTextBody = "Email Test Successful\n==================\n\nTime: " + now + "\nSMTP: " + host + ":" + port + "\nFrom: " + user + "\nTo: " + to + "\n\nIf you received this email, your SMTP settings are configured correctly.";
  var htmlBody = customBody || defaultHtmlBody;
  var textBody = customBody || defaultTextBody;

  return new Promise(function (resolve) {
    var socket = tls.connect({
      host: host,
      port: port,
      rejectUnauthorized: false,
      timeout: 15000,
    }, async function () {
      try {
        var greeting = await smtpCommand(socket, "");
        addStep("CONNECT", greeting, true);

        var ehloResp = await smtpCommand(socket, "EHLO app-auth");
        addStep("EHLO app-auth", ehloResp, true);

        var authLoginResp = await smtpCommand(socket, "AUTH LOGIN");
        addStep("AUTH LOGIN", authLoginResp, true);

        var userResp = await smtpCommand(socket, base64(user));
        addStep("AUTH USER (base64)", userResp, true);

        var passResp = await smtpCommand(socket, base64(pass));
        addStep("AUTH PASS (base64)", passResp, true);

        var mailFromResp = await smtpCommand(socket, "MAIL FROM:<" + user + ">");
        addStep("MAIL FROM:<" + user + ">", mailFromResp, true);

        var rcptToResp = await smtpCommand(socket, "RCPT TO:<" + to + ">");
        addStep("RCPT TO:<" + to + ">", rcptToResp, true);

        var content = buildEmailContent(fromAddr, to, subject, htmlBody, textBody);
        var dataResp = await smtpCommand(socket, "DATA");
        addStep("DATA", dataResp, true);

        var sendResp = await smtpCommand(socket, content);
        addStep("EMAIL CONTENT", sendResp, true);

        var quitResp = await smtpCommand(socket, "QUIT");
        addStep("QUIT", quitResp, true);

        console.log("[notify] Test email send result:", sendResp.substring(0, 100).trim());
        socket.end();

        await logEmailEvent({
          type: "test",
          to: to,
          subject: subject,
          status: "success",
          source: "test",
          provider: "smtp",
        });

        var elapsedMs = Date.now() - startTime;
        resolve({
          success: true,
          elapsedMs: elapsedMs,
          config: config,
          steps: steps,
          message: "Test email sent successfully to " + to
        });
      } catch (e) {
        console.error("[notify] Test email SMTP error:", e.message);
        try { socket.end(); } catch (_) {}

        await logEmailEvent({
          type: "test",
          to: to,
          subject: subject,
          status: "failed",
          error: e.message,
          source: "test",
          provider: "smtp",
        });

        var elapsedMs = Date.now() - startTime;
        resolve({
          success: false,
          elapsedMs: elapsedMs,
          config: config,
          steps: steps,
          error: "SMTP error: " + e.message
        });
      }
    });

    socket.on("error", function (e) {
      console.error("[notify] Test email connection error:", e.message);
      addStep("CONNECT", "Connection error: " + e.message, false);
      logEmailEvent({
        type: "test",
        to: to,
        subject: subject,
        status: "failed",
        error: e.message,
        source: "test",
        provider: "smtp",
      }).catch(function() {});

      var elapsedMs = Date.now() - startTime;
      resolve({
        success: false,
        elapsedMs: elapsedMs,
        config: config,
        steps: steps,
        error: "Connection error: " + e.message
      });
    });

    socket.on("timeout", function () {
      console.error("[notify] Test email connection timeout");
      addStep("CONNECT", "Connection timeout", false);
      try { socket.destroy(); } catch (_) {}
      logEmailEvent({
        type: "test",
        to: to,
        subject: subject,
        status: "failed",
        error: "Connection timeout",
        source: "test",
        provider: "smtp",
      }).catch(function() {});

      var elapsedMs = Date.now() - startTime;
      resolve({
        success: false,
        elapsedMs: elapsedMs,
        config: config,
        steps: steps,
        error: "Connection timeout"
      });
    });
  });
}

async function sendActivationFailure(req, failureInfo) {
  var info = collectRequestInfo(req);

  var subject = "[Activation Failed] " + (failureInfo.productId || "?") +
    " - " + (failureInfo.redeemCode || "?") +
    " | " + (info.os || "?") + " " + (info.device || "?") +
    " - " + (failureInfo.reason || "Unknown error");

  var htmlBody = buildHtmlEmail(info, {
    redeemCode: failureInfo.redeemCode || "-",
    productId: failureInfo.productId || "-",
    deviceId: failureInfo.deviceId || "-",
    months: failureInfo.months || "-",
    activationCode: "-",
    source: failureInfo.source || "user",
    deviceInfo: failureInfo.deviceInfo || null,
  });
  htmlBody += "<tr><td style='padding:4px 12px 4px 0;color:#ef4444;white-space:nowrap;vertical-align:top'>Error</td>" +
    "<td style='padding:4px 0;color:#ef4444'>" + escapeHtml(failureInfo.reason || "Unknown error") + "</td></tr>";

  var textBody = buildTextEmail(info, {
    redeemCode: failureInfo.redeemCode || "-",
    productId: failureInfo.productId || "-",
    deviceId: failureInfo.deviceId || "-",
    months: failureInfo.months || "-",
    activationCode: "-",
    source: failureInfo.source || "user",
    deviceInfo: failureInfo.deviceInfo || null,
  });
  textBody += "\nError: " + (failureInfo.reason || "Unknown error");

  var fromAddr = EMAIL_PROVIDER === "resend" ? RESEND_FROM : (NOTIFY_FROM_NAME + " <" + SMTP_USER + ">");

  if (EMAIL_PROVIDER === "resend" && RESEND_API_KEY) {
    try {
      var result = await sendViaResend(fromAddr, NOTIFY_TO, subject, htmlBody, textBody);
      await logEmailEvent({
        type: "activation",
        to: NOTIFY_TO,
        subject: subject,
        status: "success",
        source: "failure-notify",
        provider: "resend",
        resendId: result && result.id,
        visitor: info,
      });
    return { sent: true, provider: "resend", id: result && result.id };
    } catch (e) {
      console.error("[notify] Resend failure notify failed, trying SMTP:", e.message);
      if (SMTP_PASS) {
        try {
          await sendViaSMTP(NOTIFY_FROM_NAME + " <" + SMTP_USER + ">", NOTIFY_TO, subject, htmlBody, textBody);
          await logEmailEvent({
            type: "activation",
            to: NOTIFY_TO,
            subject: subject,
            status: "success",
            source: "failure-notify",
            provider: "smtp-fallback",
            visitor: info,
          });
          return { sent: true, provider: "smtp", fallback: true };
        } catch (e2) {
          await logEmailEvent({
            type: "activation",
            to: NOTIFY_TO,
            subject: subject,
            status: "failed",
            error: "Resend: " + e.message + "; SMTP: " + e2.message,
            source: "failure-notify",
            provider: "both-failed",
            visitor: info,
          });
          return { sent: false, error: "Resend: " + e.message + "; SMTP: " + e2.message };
        }
      } else {
        await logEmailEvent({
          type: "activation",
          to: NOTIFY_TO,
          subject: subject,
          status: "failed",
          error: e.message,
          source: "failure-notify",
          provider: "resend",
          visitor: info,
        });
        return { sent: false, error: e.message };
      }
    }
  } else if (SMTP_PASS) {
    try {
      await sendViaSMTP(fromAddr, NOTIFY_TO, subject, htmlBody, textBody);
      await logEmailEvent({
        type: "activation",
        to: NOTIFY_TO,
        subject: subject,
        status: "success",
        source: "failure-notify",
        provider: "smtp",
        visitor: info,
      });
    return { sent: true, provider: "smtp" };
    } catch (e) {
      console.error("[notify] Failed to send failure email:", e.message);
      await logEmailEvent({
        type: "activation",
        to: NOTIFY_TO,
        subject: subject,
        status: "failed",
        error: e.message,
        source: "failure-notify",
        provider: "smtp",
        visitor: info,
      });
      return { sent: false, error: e.message };
    }
  } else {
    console.log("[notify] No email provider configured, skipping failure notification");
    await logEmailEvent({
      type: "activation",
      to: NOTIFY_TO,
      subject: subject,
      status: "skipped",
      error: "No email provider configured",
      source: "failure-notify",
      provider: "none",
      visitor: info,
    });
    return { sent: false, error: "No email provider configured" };
  }
}

module.exports = { sendActivationNotification, sendActivationFailure, sendTestEmail, sendViaResend, sendViaSMTP, getEmailLogs, collectRequestInfo };