// lib/notify.js - Email notification for activation events
// Uses Resend API (resend.com) to send email to rinuo@qq.com
// Falls back to console.log if RESEND_API_KEY is not configured

var https = require("https");

var NOTIFY_TO = "rinuo@qq.com";
var NOTIFY_FROM = "app-auth <notify@guomengtao.com>";

function parseUserAgent(ua) {
  if (!ua) return "Unknown";
  var os = "Unknown";
  if (/Windows/i.test(ua)) os = "Windows";
  else if (/Mac/i.test(ua) || /Macintosh/i.test(ua)) os = "macOS";
  else if (/Linux/i.test(ua) && !/Android/i.test(ua)) os = "Linux";
  else if (/Android/i.test(ua)) os = "Android";
  else if (/iPhone|iPad|iOS/i.test(ua)) os = "iOS";

  var browser = "Unknown";
  if (/Edg\//i.test(ua)) browser = "Edge";
  else if (/Chrome/i.test(ua) && !/Edg\//i.test(ua)) browser = "Chrome";
  else if (/Safari/i.test(ua)) browser = "Safari";
  else if (/Firefox/i.test(ua)) browser = "Firefox";
  else if (/OPR/i.test(ua)) browser = "Opera";

  var device = "Desktop";
  if (/Mobi|Android|iPhone|iPad/i.test(ua)) device = "Mobile";

  return { os: os, browser: browser, device: device, raw: ua };
}

function collectRequestInfo(req) {
  var headers = req.headers || {};
  var ua = parseUserAgent(headers["user-agent"] || "");

  var ip = headers["x-real-ip"] ||
    headers["x-forwarded-for"] ||
    (req.connection && req.connection.remoteAddress) ||
    (req.socket && req.socket.remoteAddress) ||
    "Unknown";

  if (ip && ip.indexOf(",") > -1) {
    ip = ip.split(",")[0].trim();
  }

  return {
    ip: ip,
    userAgent: ua.raw,
    os: ua.os,
    browser: ua.browser,
    device: ua.device,
    referer: headers["referer"] || headers["referrer"] || "",
    origin: headers["origin"] || "",
    host: headers["host"] || "",
    language: headers["accept-language"] || "",
    time: new Date().toISOString(),
  };
}

function buildHtmlEmail(info, activationResult) {
  var rows = [
    ["Time", info.time],
    ["IP Address", info.ip],
    ["OS", info.os],
    ["Browser", info.browser],
    ["Device", info.device],
    ["Referer", info.referer || "(direct)"],
    ["Origin", info.origin || "-"],
    ["Host", info.host || "-"],
    ["Language", info.language || "-"],
    ["", ""],
    ["Redeem Code", activationResult.redeemCode || "-"],
    ["Product ID", activationResult.productId || "-"],
    ["Device ID", activationResult.deviceId || "-"],
    ["Months", activationResult.months || "-"],
    ["Activation Code", activationResult.activationCode || "-"],
  ];

  if (activationResult.source) {
    rows.push(["Source", activationResult.source]);
  }

  var rowHtml = rows.map(function (r) {
    return "<tr><td style='padding:4px 12px 4px 0;color:#64748b;white-space:nowrap;vertical-align:top'>" +
      r[0] + "</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>" + r[1] + "</td></tr>";
  }).join("");

  return "<div style='font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px'>" +
    "<h2 style='color:#1e293b;border-bottom:2px solid #3b82f6;padding-bottom:8px'>New Activation</h2>" +
    "<table style='border-collapse:collapse;width:100%'>" + rowHtml + "</table>" +
    "<p style='color:#94a3b8;font-size:12px;margin-top:20px'>Auto-generated by app-auth system</p>" +
    "</div>";
}

function buildTextEmail(info, activationResult) {
  var lines = [
    "New Activation",
    "==============",
    "",
    "Time: " + info.time,
    "IP: " + info.ip,
    "OS: " + info.os,
    "Browser: " + info.browser,
    "Device: " + info.device,
    "Referer: " + (info.referer || "(direct)"),
    "Origin: " + (info.origin || "-"),
    "Host: " + (info.host || "-"),
    "Language: " + (info.language || "-"),
    "",
    "Redeem Code: " + (activationResult.redeemCode || "-"),
    "Product ID: " + (activationResult.productId || "-"),
    "Device ID: " + (activationResult.deviceId || "-"),
    "Months: " + (activationResult.months || "-"),
    "Activation Code: " + (activationResult.activationCode || "-"),
  ];
  if (activationResult.source) {
    lines.push("Source: " + activationResult.source);
  }
  return lines.join("\n");
}

async function sendViaResend(apiKey, subject, htmlBody, textBody) {
  return new Promise(function (resolve, reject) {
    var payload = JSON.stringify({
      from: NOTIFY_FROM,
      to: [NOTIFY_TO],
      subject: subject,
      html: htmlBody,
      text: textBody,
    });

    var req = https.request({
      hostname: "api.resend.com",
      path: "/emails",
      method: "POST",
      headers: {
        "Authorization": "Bearer " + apiKey,
        "Content-Type": "application/json",
        "Content-Length": Buffer.byteLength(payload),
      },
      timeout: 8000,
    }, function (res) {
      var data = "";
      res.on("data", function (c) { data += c; });
      res.on("end", function () {
        if (res.statusCode >= 200 && res.statusCode < 300) {
          console.log("[notify] Email sent via Resend, status=" + res.statusCode);
          resolve(true);
        } else {
          console.error("[notify] Resend API error: status=" + res.statusCode + " body=" + data.substring(0, 200));
          resolve(false);
        }
      });
    });

    req.on("error", function (e) {
      console.error("[notify] Resend request error:", e.message);
      resolve(false);
    });

    req.on("timeout", function () {
      req.destroy();
      console.error("[notify] Resend request timeout");
      resolve(false);
    });

    req.write(payload);
    req.end();
  });
}

async function sendActivationNotification(req, activationResult) {
  var info = collectRequestInfo(req);
  var subject = "[Activation] " + (activationResult.productId || "?") +
    " - " + (activationResult.redeemCode || "?") +
    " | " + (info.os || "?") + " " + (info.device || "?");

  var htmlBody = buildHtmlEmail(info, activationResult);
  var textBody = buildTextEmail(info, activationResult);

  var apiKey = process.env.RESEND_API_KEY || "";

  if (apiKey) {
    try {
      await sendViaResend(apiKey, subject, htmlBody, textBody);
    } catch (e) {
      console.error("[notify] Failed to send email:", e.message);
    }
  } else {
    console.log("[notify] RESEND_API_KEY not configured, logging instead:");
    console.log("[notify] Subject:", subject);
    console.log("[notify] Body:", textBody);
  }
}

module.exports = { sendActivationNotification, collectRequestInfo };