// lib/notify.js - Email notification for activation events
// Uses QQ SMTP (smtp.qq.com:465 SSL) to send email to rinuo@qq.com
// Falls back to console.log if SMTP is not configured

var tls = require("tls");

var SMTP_HOST = process.env.SMTP_HOST || "smtp.qq.com";
var SMTP_PORT = parseInt(process.env.SMTP_PORT || "465", 10);
var SMTP_USER = process.env.SMTP_USER || "rinuo@qq.com";
var SMTP_PASS = process.env.SMTP_PASS || "";
var NOTIFY_TO = process.env.NOTIFY_TO || "rinuo@qq.com";
var NOTIFY_FROM_NAME = process.env.NOTIFY_FROM_NAME || "app-auth";

var EMAIL_LOG_KEY = "auth:email_logs";
var EMAIL_LOG_MAX = 100;

function getRedis() {
  try {
    return require("./redis");
  } catch (e) {
    return null;
  }
}

function escapeHtml(str) {
  if (!str) return "";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function parseUserAgent(ua) {
  if (!ua) return "Unknown";
  var os = "Unknown";
  if (/Windows/i.test(ua)) os = "Windows";
  else if (/Mac/i.test(ua) || /Macintosh/i.test(ua)) os = "macOS";
  else if (/Linux/i.test(ua) && !/Android/i.test(ua)) os = "Linux";
  else if (/Android/i.test(ua)) os = "Android";
  else if (/iPhone|iPad|iOS/i.test(ua)) os = "iOS";

  var browser = "Unknown";
  if (/Edg\//i.test(ua)) browser = "Edge";
  else if (/Chrome/i.test(ua) && !/Edg\//i.test(ua)) browser = "Chrome";
  else if (/Safari/i.test(ua)) browser = "Safari";
  else if (/Firefox/i.test(ua)) browser = "Firefox";
  else if (/OPR/i.test(ua)) browser = "Opera";

  var device = "Desktop";
  if (/Mobi|Android|iPhone|iPad/i.test(ua)) device = "Mobile";

  return { os: os, browser: browser, device: device, raw: ua };
}

function collectRequestInfo(req) {
  var headers = req.headers || {};
  var ua = parseUserAgent(headers["user-agent"] || "");

  var ip = headers["x-real-ip"] ||
    headers["x-forwarded-for"] ||
    (req.connection && req.connection.remoteAddress) ||
    (req.socket && req.socket.remoteAddress) ||
    "Unknown";

  if (ip && ip.indexOf(",") > -1) {
    ip = ip.split(",")[0].trim();
  }

  return {
    ip: ip,
    userAgent: ua.raw,
    os: ua.os,
    browser: ua.browser,
    device: ua.device,
    referer: headers["referer"] || headers["referrer"] || "",
    origin: headers["origin"] || "",
    host: headers["host"] || "",
    language: headers["accept-language"] || "",
    time: new Date().toISOString(),
  };
}

function buildHtmlEmail(info, activationResult) {
  var rows = [
    ["Time", info.time],
    ["IP Address", info.ip],
    ["OS", info.os],
    ["Browser", info.browser],
    ["Device", info.device],
    ["Referer", info.referer || "(direct)"],
    ["Origin", info.origin || "-"],
    ["Host", info.host || "-"],
    ["Language", info.language || "-"],
    ["", ""],
    ["Redeem Code", activationResult.redeemCode || "-"],
    ["Product ID", activationResult.productId || "-"],
    ["Device ID", activationResult.deviceId || "-"],
    ["Months", activationResult.months || "-"],
    ["Activation Code", activationResult.activationCode || "-"],
  ];

  if (activationResult.source) {
    rows.push(["Source", activationResult.source]);
  }

  var rowHtml = rows.map(function (r) {
    return "<tr><td style='padding:4px 12px 4px 0;color:#64748b;white-space:nowrap;vertical-align:top'>" +
      r[0] + "</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>" + r[1] + "</td></tr>";
  }).join("");

  return "<div style='font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px'>" +
    "<h2 style='color:#1e293b;border-bottom:2px solid #3b82f6;padding-bottom:8px'>New Activation</h2>" +
    "<table style='border-collapse:collapse;width:100%'>" + rowHtml + "</table>" +
    "<p style='color:#94a3b8;font-size:12px;margin-top:20px'>Auto-generated by app-auth system</p>" +
    "</div>";
}

function buildTextEmail(info, activationResult) {
  var lines = [
    "New Activation",
    "==============",
    "",
    "Time: " + info.time,
    "IP: " + info.ip,
    "OS: " + info.os,
    "Browser: " + info.browser,
    "Device: " + info.device,
    "Referer: " + (info.referer || "(direct)"),
    "Origin: " + (info.origin || "-"),
    "Host: " + (info.host || "-"),
    "Language: " + (info.language || "-"),
    "",
    "Redeem Code: " + (activationResult.redeemCode || "-"),
    "Product ID: " + (activationResult.productId || "-"),
    "Device ID: " + (activationResult.deviceId || "-"),
    "Months: " + (activationResult.months || "-"),
    "Activation Code: " + (activationResult.activationCode || "-"),
  ];
  if (activationResult.source) {
    lines.push("Source: " + activationResult.source);
  }
  return lines.join("\n");
}

function base64(str) {
  return Buffer.from(str, "utf-8").toString("base64");
}

function buildEmailContent(fromAddr, toAddr, subject, htmlBody, textBody) {
  var boundary = "==boundary_" + Date.now() + "_" + Math.random().toString(36).slice(2);
  var lines = [
    "From: " + fromAddr,
    "To: " + toAddr,
    "Subject: =?UTF-8?B?" + base64(subject) + "?=",
    "MIME-Version: 1.0",
    "Content-Type: multipart/alternative; boundary=\"" + boundary + "\"",
    "",
    "--" + boundary,
    "Content-Type: text/plain; charset=UTF-8",
    "Content-Transfer-Encoding: base64",
    "",
  ];

  var textLines = textBody.split("\n");
  for (var i = 0; i < textLines.length; i++) {
    lines.push(base64(textLines[i] + "\r\n"));
  }

  lines.push("");
  lines.push("--" + boundary);
  lines.push("Content-Type: text/html; charset=UTF-8");
  lines.push("Content-Transfer-Encoding: base64");
  lines.push("");

  var htmlLines = htmlBody.split("\n");
  for (var j = 0; j < htmlLines.length; j++) {
    lines.push(base64(htmlLines[j] + "\r\n"));
  }

  lines.push("");
  lines.push("--" + boundary + "--");
  lines.push(".");

  return lines.join("\r\n");
}

function smtpCommand(socket, cmd) {
  return new Promise(function (resolve, reject) {
    var onData = function (data) {
      var text = data.toString();
      socket.removeListener("data", onData);
      resolve(text);
    };
    socket.on("data", onData);
    socket.write(cmd + "\r\n");
  });
}

async function sendViaSMTP(fromAddr, toAddr, subject, htmlBody, textBody) {
  return new Promise(function (resolve, reject) {
    var socket = tls.connect({
      host: SMTP_HOST,
      port: SMTP_PORT,
      rejectUnauthorized: false,
      timeout: 15000,
    }, async function () {
      try {
        var greeting = await smtpCommand(socket, "");
        console.log("[notify] SMTP greeting:", greeting.substring(0, 100).trim());

        await smtpCommand(socket, "EHLO app-auth");
        await smtpCommand(socket, "AUTH LOGIN");
        await smtpCommand(socket, base64(SMTP_USER));
        await smtpCommand(socket, base64(SMTP_PASS));

        await smtpCommand(socket, "MAIL FROM:<" + SMTP_USER + ">");
        await smtpCommand(socket, "RCPT TO:<" + toAddr + ">");

        var content = buildEmailContent(fromAddr, toAddr, subject, htmlBody, textBody);
        await smtpCommand(socket, "DATA");
        var result = await smtpCommand(socket, content);

        await smtpCommand(socket, "QUIT");

        console.log("[notify] SMTP send result:", result.substring(0, 100).trim());
        socket.end();
        resolve(true);
      } catch (e) {
        console.error("[notify] SMTP error:", e.message);
        try { socket.end(); } catch (_) {}
        resolve(false);
      }
    });

    socket.on("error", function (e) {
      console.error("[notify] SMTP connection error:", e.message);
      resolve(false);
    });

    socket.on("timeout", function () {
      console.error("[notify] SMTP connection timeout");
      try { socket.destroy(); } catch (_) {}
      resolve(false);
    });
  });
}

async function logEmailEvent(entry) {
  try {
    var redis = getRedis();
    if (!redis) return;
    var record = JSON.stringify({
      time: new Date().toISOString(),
      type: entry.type || "info",
      to: entry.to || NOTIFY_TO,
      subject: entry.subject || "",
      status: entry.status || "sent",
      error: entry.error || "",
      source: entry.source || "activation",
      visitor: entry.visitor || null,
    });
    await redis.lpush(EMAIL_LOG_KEY, record);
    await redis.ltrim(EMAIL_LOG_KEY, 0, EMAIL_LOG_MAX - 1);
  } catch (e) {
    console.error("[notify] Failed to log email event:", e.message);
  }
}

async function getEmailLogs(limit) {
  try {
    var redis = getRedis();
    if (!redis) return [];
    var lim = Math.min(limit || 50, 200);
    var raw = await redis.lrange(EMAIL_LOG_KEY, 0, lim - 1);
    if (!Array.isArray(raw)) return [];
    return raw.map(function(r) {
      try { return JSON.parse(r); } catch (_) { return null; }
    }).filter(Boolean);
  } catch (e) {
    console.error("[notify] Failed to get email logs:", e.message);
    return [];
  }
}

async function sendActivationNotification(req, activationResult) {
  var info = collectRequestInfo(req);
  var subject = "[Activation] " + (activationResult.productId || "?") +
    " - " + (activationResult.redeemCode || "?") +
    " | " + (info.os || "?") + " " + (info.device || "?");

  var htmlBody = buildHtmlEmail(info, activationResult);
  var textBody = buildTextEmail(info, activationResult);

  var fromAddr = NOTIFY_FROM_NAME + " <" + SMTP_USER + ">";

  if (SMTP_PASS) {
    try {
      await sendViaSMTP(fromAddr, NOTIFY_TO, subject, htmlBody, textBody);
      await logEmailEvent({
        type: "activation",
        to: NOTIFY_TO,
        subject: subject,
        status: "success",
        source: "activation",
        visitor: info,
      });
    } catch (e) {
      console.error("[notify] Failed to send email:", e.message);
      await logEmailEvent({
        type: "activation",
        to: NOTIFY_TO,
        subject: subject,
        status: "failed",
        error: e.message,
        source: "activation",
        visitor: info,
      });
    }
  } else {
    console.log("[notify] SMTP_PASS not configured, logging instead:");
    console.log("[notify] Subject:", subject);
    console.log("[notify] Body:", textBody);
    await logEmailEvent({
      type: "activation",
      to: NOTIFY_TO,
      subject: subject,
      status: "skipped",
      error: "SMTP_PASS not configured",
      source: "activation",
      visitor: info,
    });
  }
}

async function sendTestEmail(options) {
  var host = options.smtpHost || SMTP_HOST;
  var port = options.smtpPort || SMTP_PORT;
  var user = options.smtpUser || SMTP_USER;
  var pass = options.smtpPass || SMTP_PASS;
  var to = options.notifyTo || NOTIFY_TO;
  var fromName = options.notifyFromName || NOTIFY_FROM_NAME;

  if (!pass) {
    throw new Error("SMTP password is not configured");
  }

  var fromAddr = fromName + " <" + user + ">";
  var subject = "[Test] app-auth Email Notification Test";
  var now = new Date().toISOString();
  var htmlBody = "<div style='font-family:-apple-system,BlinkMacSystemFont,sans-serif;max-width:600px'>" +
    "<h2 style='color:#10b981;border-bottom:2px solid #10b981;padding-bottom:8px'>Email Test Successful</h2>" +
    "<p style='color:#374151;font-size:14px'>This is a test email from the app-auth system.</p>" +
    "<table style='border-collapse:collapse;width:100%;margin-top:16px'>" +
    "<tr><td style='padding:4px 12px 4px 0;color:#64748b'>Time</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>" + now + "</td></tr>" +
    "<tr><td style='padding:4px 12px 4px 0;color:#64748b'>SMTP Server</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>" + host + ":" + port + "</td></tr>" +
    "<tr><td style='padding:4px 12px 4px 0;color:#64748b'>From</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>" + user + "</td></tr>" +
    "<tr><td style='padding:4px 12px 4px 0;color:#64748b'>To</td><td style='padding:4px 0;font-family:monospace;font-size:13px'>" + to + "</td></tr>" +
    "</table>" +
    "<p style='color:#94a3b8;font-size:12px;margin-top:20px'>If you received this email, your SMTP settings are configured correctly.</p>" +
    "</div>";
  var textBody = "Email Test Successful\n==================\n\nTime: " + now + "\nSMTP: " + host + ":" + port + "\nFrom: " + user + "\nTo: " + to + "\n\nIf you received this email, your SMTP settings are configured correctly.";

  return new Promise(function (resolve, reject) {
    var socket = tls.connect({
      host: host,
      port: port,
      rejectUnauthorized: false,
      timeout: 15000,
    }, async function () {
      try {
        await smtpCommand(socket, "");
        await smtpCommand(socket, "EHLO app-auth");
        await smtpCommand(socket, "AUTH LOGIN");
        await smtpCommand(socket, base64(user));
        await smtpCommand(socket, base64(pass));
        await smtpCommand(socket, "MAIL FROM:<" + user + ">");
        await smtpCommand(socket, "RCPT TO:<" + to + ">");

        var content = buildEmailContent(fromAddr, to, subject, htmlBody, textBody);
        await smtpCommand(socket, "DATA");
        var result = await smtpCommand(socket, content);

        await smtpCommand(socket, "QUIT");

        console.log("[notify] Test email send result:", result.substring(0, 100).trim());
        socket.end();
        await logEmailEvent({
          type: "test",
          to: to,
          subject: subject,
          status: "success",
          source: "test",
        });
        resolve(true);
      } catch (e) {
        console.error("[notify] Test email SMTP error:", e.message);
        try { socket.end(); } catch (_) {}
        await logEmailEvent({
          type: "test",
          to: to,
          subject: subject,
          status: "failed",
          error: e.message,
          source: "test",
        });
        reject(new Error("SMTP error: " + e.message));
      }
    });

    socket.on("error", function (e) {
      console.error("[notify] Test email connection error:", e.message);
      logEmailEvent({
        type: "test",
        to: to,
        subject: subject,
        status: "failed",
        error: e.message,
        source: "test",
      }).catch(function() {});
      reject(new Error("Connection error: " + e.message));
    });

    socket.on("timeout", function () {
      console.error("[notify] Test email connection timeout");
      try { socket.destroy(); } catch (_) {}
      logEmailEvent({
        type: "test",
        to: to,
        subject: subject,
        status: "failed",
        error: "Connection timeout",
        source: "test",
      }).catch(function() {});
      reject(new Error("Connection timeout"));
    });
  });
}

async function sendActivationFailure(req, failureInfo) {
  var info = collectRequestInfo(req);
  var subject = "[Activation Failed] " + (failureInfo.productId || "?") +
    " - " + (failureInfo.redeemCode || "?") +
    " | " + (info.os || "?") + " " + (info.device || "?") +
    " - " + (failureInfo.reason || "Unknown error");

  var htmlBody = buildHtmlEmail(info, {
    redeemCode: failureInfo.redeemCode || "-",
    productId: failureInfo.productId || "-",
    deviceId: failureInfo.deviceId || "-",
    months: failureInfo.months || "-",
    activationCode: "-",
    source: failureInfo.source || "user",
  });
  htmlBody += "<tr><td style='padding:4px 12px 4px 0;color:#ef4444;white-space:nowrap;vertical-align:top'>Error</td>" +
    "<td style='padding:4px 0;color:#ef4444'>" + escapeHtml(failureInfo.reason || "Unknown error") + "</td></tr>";

  var textBody = buildTextEmail(info, {
    redeemCode: failureInfo.redeemCode || "-",
    productId: failureInfo.productId || "-",
    deviceId: failureInfo.deviceId || "-",
    months: failureInfo.months || "-",
    activationCode: "-",
    source: failureInfo.source || "user",
  });
  textBody += "\nError: " + (failureInfo.reason || "Unknown error");

  var fromAddr = NOTIFY_FROM_NAME + " <" + SMTP_USER + ">";

  if (SMTP_PASS) {
    try {
      await sendViaSMTP(fromAddr, NOTIFY_TO, subject, htmlBody, textBody);
      await logEmailEvent({
        type: "activation",
        to: NOTIFY_TO,
        subject: subject,
        status: "success",
        source: "failure-notify",
        visitor: info,
      });
    } catch (e) {
      console.error("[notify] Failed to send failure email:", e.message);
      await logEmailEvent({
        type: "activation",
        to: NOTIFY_TO,
        subject: subject,
        status: "failed",
        error: e.message,
        source: "failure-notify",
        visitor: info,
      });
    }
  } else {
    console.log("[notify] Activation failure:", failureInfo.reason);
    await logEmailEvent({
      type: "activation",
      to: NOTIFY_TO,
      subject: subject,
      status: "skipped",
      error: failureInfo.reason || "Unknown error",
      source: "failure-notify",
      visitor: info,
    });
  }
}

module.exports = { sendActivationNotification, sendActivationFailure, sendTestEmail, getEmailLogs, collectRequestInfo };